name = "myccc-cycling-calculator"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Static assets configuration
[assets]
directory = "web"

[env.production]
name = "myccc-cycling-calculator"

[env.development]
name = "myccc-cycling-calculator-dev"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "cycling-data"
database_id = "your-database-id-here"

# Variables
[vars]
ENVIRONMENT = "production"

# KV for file storage (optional)
# [[kv_namespaces]]
# binding = "FILES"
# id = "your-kv-namespace-id"

# R2 bucket for file storage (alternative to KV)
# [[r2_buckets]]
# binding = "UPLOADS"
# bucket_name = "myccc-uploads"